---
title: Notes
output: html_document
---
Notes and to-do written 2026-01-06 after version 4.3.0:

# Package Notes:

3.    _Integration_: You use Simpsons 1/3 composite rule in version >4.0.0.  However, it appears that `stats::integrate` provides better precision than Simpson's rule and is very fast.  Consider changing the numerical integration methods to use `stats::integrate`.  You would do this by defining an internal function F that calls the `<function>.like` function, then call `stats::integrate` with F. 

4.  _For the record_: Simpson's alternate composite formula. https://en.wikipedia.org/wiki/Simpson's_rule
$$
(dx/48) * (17f(x_0) + 59f(x_1) + 43f(x_2) + 49f(x_3) + 48f(x_4) + 48f(x_5) + ...
          + 48f(x_n-4) + 49f(x_n-3) + 43f(x_n-2) + 59f(x_n-1) + 17f(x_n))
$$
3.    _Density smoother_: Implement smooth likelihoods again.
4.    _Circles in plots_ : At present, covariates associated with distances are not used to plot circles. This means if distance i is from observer 1, it will get plotted on all drawn distance functions including those from observer 2 or 3.  Consider fixing this and only plot distances from observations associated with covariates being plotted. That is, figure out which observations are associated with the requested covariate classes in `newdata`. If you do this, you could also plot bars associated with the covariate classes. This is complicated because you will need to tidyr::unite covariate values in the `newdata` and the `model.matrix` and figure out which rows from `model.matrix` are associated with which rows in `newdata`.  Factors are easy.  For numeric covariates, you can say a distance is associated with a numeric value of X if it is within 1 standard deviation of X. 
5.    _Testing Versus Distance_: Check parameter values and log likelihoods of every likelihood against what `distance` gives. 
7.    _Two param likelihoods_: At some stage, after Rdistance is out, consider including two equations for parameters of likelihoods with two parameters.  E.g., one formula for 'beta' of Huber likelihood and another for 'gamma', e.g., `beta ~ observer` and `gamma ~ observer`. I think this will require a whole new estimation function. 
1.    _Logistic, Uniform, Triangle, and Huber Likelihoods_: Implement logistic and uniform likelihoods.  You took them out of version 4.0.0. I think you need to use the EM algorithm. See next note. You placed the old versions in `CodeParkingLot/OtherLikelihoods`.


9.  *Stepwise variable selection*: Write `add1` and `drop1` and `extractAIC` so that `step` function will work with distance function objects. 


# Testing:

You have most of these testing files drafted in `Rdistance/CodeParkingLot/tests/version3.1.1`.


3.    Test methods for all the options (those set in `onLoad`)
4.    Test methods for `type = density` in `predict(dfunc)`
7.    Tests that check against `distance::ds` and other routines.  This should become a vignette or paper. 
8.    Test for the 'sml antelope' combined distance method that uses NA distances and NA length transects.

# Missing values:

Make this into a tutorial or post on your blog.
Missing values in an observation contribute to either distance function estimation ('dfunc') or abundance estimation ('abundance') as follows: 

```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'}
tabl <- "
| Distance        | Group Size  | Transect len  | Contributes to:  | Comment                   |
|:---------------:|:-----------:|:-------------:|:----------------:|:-------------------------:|
|  present        |   present   |   present     | dfunc; abundance | usual observation         |
|  MISSING        |   present   |   present     | abundance        |                           |
|  present        |   MISSING   |   present     | dfunc; abundance |for abundance, length only |
|  present        |   present   |   MISSING     | dfunc; abundance |  sum groupsizes |
|  MISSING        |   MISSING   |   present     | abundance        |   so-called zero transect |
|  present        |   MISSING   |   MISSING     | dfunc            |                           |
|  MISSING        |   present   |   MISSING     | nothing          | *ignored*                 |
|  MISSING        |   MISSING   |   MISSING     | nothing          | *does not happen*         |
"

cat(tabl) # output the table in a format good for HTML/PDF/docx conversion
```

Group size values never contribute to distance function estimation. Distance functions are estimated from distances only. 

# Variance of Density

Trent ran across the variance of density in a camera trap paper (Moeller et al 2018 "Three novel..."). The "IS" camera trap method is parallel to distance sampling. Variance in the Moeller paper says this, "Because fixed-area point counts are special
cases of fixed-area transects, we estimated variance of the parameter $\hat{D}$ based on the formula for random line transects of
unequal lengths (Thompson 2002, Fewster et al. 2009), following:"
$$
\widehat{Var}(\hat{D}) = \frac{M}{L^2(M-1)}\sum_{i=1}^M (Ja_i)^2 \left(\frac{n_i}{Ja_i} - \frac{n}{L}\right)^2
$$
where $Ja_i$ is the summed area of camera i across all occasions, $L = \sum_{i=1}^M Ja_i$, count $n_i$ is the count
of animals over all occasions at camera i, and $n$ is the total count of animals over all cameras and occasions. We then estimated the variance of $\hat{N}$ using the delta method. 

Look up Thompson 2002 and Fewster et al 2009 and see if these formula agree with what's in Distance. 

Thompson, S. K. 2002. Sampling. Second edition. John Wiley & Sons Inc, New York, New York, USA.

Fewster, R. M., S. T. Buckland, K. P. Burnham, D. L. Borchers, P. E. Jupp, J. L. Laake, and L. Thomas.
2009. Estimating the encounter rate variance in distance sampling. Biometrics 65:225–236.
