source.all <- function(){

#    source("BootstrapGMRDSmodel.R")
#    source("BootSummary.R")
#    source("dat2dist.dst")
#    source("dat2dist.txt")
#    source("dat2dist2.dst")
#    source("detection functions.R")
#    source("distance_optimize.r")
#    source("F.line.transect.R")
#    source("FitGMRDSmodel.R")
#    source("GammaMRDS-internal.R")
#    source("GoF.GMRDS.R")

    source("F.dfunc.estim.R")
    source("F.start.limits.r")
    source("cosine.expansion.R")
    source("ESW.r")
    source("halfnorm.like.R")
    source("halfnorm.nLL.R")
    source("hazrate.like.R")
    source("hazrate.nLL.R")
    source("gamma.like.R")
    source("gamma.nLL.R")
    source("hermite.expansion.R")
    source("integration.constant.R")
    source("negexp.like.R")
    source("negexp.nLL.r")
    source("plot.dfunc.r")
    source("simple.expansion.r")
    source("uniform.like.R")
    source("uniform.nll.r")
    source("coef.dfunc.r")
    source("print.dfunc.r")
    source("AIC.dfunc.r")
    source("F.gx.estim.r")
    source("F.brainless.CDS.r")
    source("F.abund.estim.r")
    source("print.abund.r")

}

source.all()
